### ISSUE TITLE
Support markdown from remote sources

### ISSUE THREAD

**Issue by jamessimone** [cowchimp/gatsby-plugin-ebook#1]
Hi there! This plugin is awesome and I'd love to use it for Markdown for nodes whose markdown is sourced remotely. The hardcoded reliance on a markdown node having both a frontmatter title and an absolute dir prevent this at the moment. For example, I wouldn't even be querying allMarkdownRemark - but the nodes I would be querying have a resolvable title, and a childMarkdownRemark node with resolvable raw markdown / html. What do you think?

**Comment by cowchimp** [comment]
Hi.
Thanks for bringing this to my attention. I didn't realize this won't work with remote sources.
I only tested this plugin against [gaearon/overreacted.io](https://github.com/gaearon/overreacted.io).

Would you be interested in submitting a PR to address this?

If not, can you clarify how to reproduce the issue so I can research it? I don't have experience spinning up a gatsby instance that fetches data from a remote data source.

Thanks.

**Comment by jamessimone** [comment]
@cowchimp for sure, no problem. It’s possible I’ll have some time this week to submit a PR. Failing that, I can for sure create a minimum example documenting what nodes would look like from a remote source like Airtable (not the source my nodes come from, but extremely popular in the Gatsby community as well).

**Comment by cowchimp** [comment]
awesome. thank you 👍
if you create a PR try to test your changes against [gaearon/overreacted.io](https://github.com/gaearon/overreacted.io) as well please.

**Comment by jamessimone** [comment]
Sounds good!

**Comment by jamessimone** [comment]
Just to follow up - I currently have the plugin "working" for remote or local sources but there are still some issues to iron out, at least for my use case. Hoping to get some code to show you in the next few days, though.

**Comment by cowchimp** [comment]
Fantastic. Thanks!
